### ISSUE TITLE
What can cause us to exit the program?

### ISSUE THREAD

**Issue by EizTimor** [EizTimor/SPSudokuFinal#14]
Almost every command uses the moves and turns lists, which to create them we need to allocate some memory using malloc. 
Do you think that if such creations fail we need to exit the program? for turns list (the whole undo/redo list) I believe so, but what about a single turn?

Same issue for cell options, its a linked list so we always manipulate some memory.

**Comment by EizTimor** [comment]
OK, I just saw that Moshe wrote on the forum that every system error (such as malloc) is a cause for exit, I will fix it for the things that I have changed.

**Comment by IdoLerer** [comment]
I added the check where it was missing in the parser. Notice there are some cases in the solver that after a malloc fail it returns 0 instead of exiting the program. I think we should change it (though doesn't really matter... I don't think there is a real chance it will fail).
