### ISSUE TITLE
Unexpected behavior on "generate"

### ISSUE THREAD

**Issue by IdoLerer** [EizTimor/SPSudokuFinal#4]
Example:
edit
generate 40 10

enters a very long loop (expected?) and returns an empty board.

**Comment by EizTimor** [comment]
This is not unexpected

> If one of the X randomly-chosen cells has no legal value available, or the resulting board has no solution (i.e., the ILP solver fails), reset the board back to its original state (before executing the command) and repeat the previous step. After 1000 such iterations, treat this as an error in the puzzle generator.

Just in cast you encounter it again, I added a print that says "MAX ITERS" so we will know it ended correctly with no solution.
