### ISSUE TITLE
guess_hint with non integers

### ISSUE THREAD

**Issue by EizTimor** [EizTimor/SPSudokuFinal#7]
When trying to do guess_hint 0.5 0.5, the validation of the command has passed successfully although they are not integers.
I think we should check every command of integers with doubles, to verify.

**Comment by IdoLerer** [comment]
I think it is fine to accept non-integers as parameters, it just floors them to integers.
The problem was that the range of the parameters in guess_hint wasn't properly checked, so it accepted "guess_hint 0 0" when it should have printed an error.
