### ISSUE TITLE
core dumped when loading board

### ISSUE THREAD

**Issue by EizTimor** [EizTimor/SPSudokuFinal#9]
When trying to load a file that doesnt exist, and then trying to load a file that do exist theres a core dumped error for double free()
commands:
1. solve 0 (a file that doesnt exist)
2. solve 1 (a file that do exist) - now core is dumped

**Comment by IdoLerer** [comment]
Fixed, the problem was that free doesn't change the pointer to null so sometimes it passed the null check and was "freed" although it wasn't allocated.
